# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.6.8-alpine
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Application testing
        env:
          FLASK_APP: app/autoapp.py
        run: |
          pwd
          ls -lah
